/**
 * Utility to fix duration metadata in WebM files generated by MediaRecorder.
 * Browsers often produce WebM containers without Duration in the EBML Info header,
 * causing gallery players and media apps to display 0s, 3s, or disable seeking.
 *
 * This utility parses the EBML tree and injects/updates the Duration element (0x4489)
 * with the exact duration in milliseconds.
 */

interface SectionInfo {
  name: string;
  type: 'Container' | 'Binary' | 'Uint' | 'Int' | 'String' | 'Float' | 'Date';
}

const SECTIONS: Record<number, SectionInfo> = {
  0xa45dfa3: { name: 'EBML', type: 'Container' },
  0x286: { name: 'EBMLVersion', type: 'Uint' },
  0x2f7: { name: 'EBMLReadVersion', type: 'Uint' },
  0x2f2: { name: 'EBMLMaxIDLength', type: 'Uint' },
  0x2f3: { name: 'EBMLMaxSizeLength', type: 'Uint' },
  0x282: { name: 'DocType', type: 'String' },
  0x287: { name: 'DocTypeVersion', type: 'Uint' },
  0x285: { name: 'DocTypeReadVersion', type: 'Uint' },
  0x6c: { name: 'Void', type: 'Binary' },
  0x3f: { name: 'CRC-32', type: 'Binary' },
  0x8538067: { name: 'Segment', type: 'Container' },
  0x14d9b74: { name: 'SeekHead', type: 'Container' },
  0xdbb: { name: 'Seek', type: 'Container' },
  0x13ab: { name: 'SeekID', type: 'Binary' },
  0x13ac: { name: 'SeekPosition', type: 'Uint' },
  0x549a966: { name: 'Info', type: 'Container' },
  0x33a4: { name: 'SegmentUID', type: 'Binary' },
  0x3384: { name: 'SegmentFilename', type: 'String' },
  0xad7b1: { name: 'TimecodeScale', type: 'Uint' },
  0x489: { name: 'Duration', type: 'Float' },
  0x461: { name: 'DateUTC', type: 'Date' },
  0x3ba9: { name: 'Title', type: 'String' },
  0xd80: { name: 'MuxingApp', type: 'String' },
  0x1741: { name: 'WritingApp', type: 'String' },
  0x67: { name: 'Timecode', type: 'Uint' },
  0x654ae6b: { name: 'Tracks', type: 'Container' },
  0x2e: { name: 'TrackEntry', type: 'Container' },
  0x57: { name: 'TrackNumber', type: 'Uint' },
  0x33c5: { name: 'TrackUID', type: 'Uint' },
  0x3: { name: 'TrackType', type: 'Uint' },
  0x23e383: { name: 'Video', type: 'Container' },
  0x61: { name: 'Audio', type: 'Container' },
};

function readVint(buffer: Uint8Array, start: number): { id: number; length: number } | null {
  if (start >= buffer.length) return null;
  const firstByte = buffer[start];
  let mask = 0x80;
  let length = 1;

  while ((firstByte & mask) === 0 && mask > 0) {
    mask >>= 1;
    length++;
  }
  if (length > 8 || start + length > buffer.length) return null;

  let value = firstByte & (mask - 1);
  for (let i = 1; i < length; i++) {
    value = (value << 8) | buffer[start + i];
  }
  return { id: value, length };
}

function readElementId(buffer: Uint8Array, start: number): { id: number; length: number } | null {
  if (start >= buffer.length) return null;
  const firstByte = buffer[start];
  let mask = 0x80;
  let length = 1;

  while ((firstByte & mask) === 0 && mask > 0) {
    mask >>= 1;
    length++;
  }
  if (length > 4 || start + length > buffer.length) return null;

  let id = 0;
  for (let i = 0; i < length; i++) {
    id = (id << 8) | buffer[start + i];
  }
  return { id, length };
}

function writeFloat64(val: number): Uint8Array {
  const buf = new ArrayBuffer(8);
  const view = new DataView(buf);
  view.setFloat64(0, val, false); // Big endian
  return new Uint8Array(buf);
}

/**
 * Injects or updates the Duration element inside the WebM Segment -> Info header.
 * @param blob Original WebM Blob from MediaRecorder
 * @param durationMs Duration of video in milliseconds
 */
export async function fixWebmDuration(blob: Blob, durationMs: number): Promise<Blob> {
  if (blob.size === 0 || durationMs <= 0) {
    return blob;
  }

  try {
    const arrayBuffer = await blob.arrayBuffer();
    const bytes = new Uint8Array(arrayBuffer);

    // Find Segment and Info containers
    let pos = 0;
    let infoPos = -1;
    let infoDataPos = -1;
    let infoSize = 0;
    let infoSizeVintLen = 0;
    let durationPos = -1;
    let durationDataPos = -1;
    let durationSize = 0;
    let timecodeScale = 1000000; // default 1ms

    while (pos < Math.min(bytes.length, 1024 * 64)) {
      const elem = readElementId(bytes, pos);
      if (!elem) break;
      const sizeVint = readVint(bytes, pos + elem.length);
      if (!sizeVint) break;

      const headerLen = elem.length + sizeVint.length;
      const dataPos = pos + headerLen;
      const dataSize = sizeVint.id;

      if (elem.id === 0x8538067) {
        // Segment container found, step inside
        pos = dataPos;
        continue;
      }

      if (elem.id === 0x549a966) {
        // Info container found
        infoPos = pos;
        infoDataPos = dataPos;
        infoSize = dataSize;
        infoSizeVintLen = sizeVint.length;

        // Scan children inside Info
        let infoChildPos = dataPos;
        const infoEnd = dataPos + dataSize;

        while (infoChildPos < infoEnd && infoChildPos < bytes.length) {
          const childElem = readElementId(bytes, infoChildPos);
          if (!childElem) break;
          const childSizeVint = readVint(bytes, infoChildPos + childElem.length);
          if (!childSizeVint) break;

          const childHeaderLen = childElem.length + childSizeVint.length;
          const childDataPos = infoChildPos + childHeaderLen;
          const childDataSize = childSizeVint.id;

          if (childElem.id === 0xad7b1) {
            // TimecodeScale
            let scale = 0;
            for (let i = 0; i < childDataSize; i++) {
              scale = (scale << 8) | bytes[childDataPos + i];
            }
            if (scale > 0) timecodeScale = scale;
          } else if (childElem.id === 0x489) {
            // Duration element already exists
            durationPos = infoChildPos;
            durationDataPos = childDataPos;
            durationSize = childDataSize;
          }

          infoChildPos = childDataPos + childDataSize;
        }
        break;
      }

      pos = dataPos + dataSize;
    }

    if (infoPos === -1) {
      // Info section not found, return original blob
      return blob;
    }

    // Calculate duration in timecode scale units (typically 1ms each)
    const durationInUnits = (durationMs * 1000000) / timecodeScale;
    const floatBytes = writeFloat64(durationInUnits);

    if (durationPos !== -1 && durationSize === 8) {
      // Direct replacement in-place
      bytes.set(floatBytes, durationDataPos);
      return new Blob([bytes] as unknown as BlobPart[], { type: blob.type || 'video/webm' });
    }

    // Otherwise, construct a new Duration element and insert it into Info
    // Duration ID = 0x4489 (2 bytes), size = 0x88 (8 bytes vint: 0x80 | 8)
    const durationElement = new Uint8Array(2 + 1 + 8);
    durationElement[0] = 0x44;
    durationElement[1] = 0x89;
    durationElement[2] = 0x88;
    durationElement.set(floatBytes, 3);

    // If duration already exists but different size, remove old one first
    let finalInfoBytes: Uint8Array;
    if (durationPos !== -1) {
      const beforeDuration = bytes.slice(infoDataPos, durationPos);
      const afterDuration = bytes.slice(durationDataPos + durationSize, infoDataPos + infoSize);
      finalInfoBytes = new Uint8Array(
        beforeDuration.length + durationElement.length + afterDuration.length
      );
      finalInfoBytes.set(beforeDuration, 0);
      finalInfoBytes.set(durationElement, beforeDuration.length);
      finalInfoBytes.set(afterDuration, beforeDuration.length + durationElement.length);
    } else {
      // Append to Info
      const currentInfoData = bytes.slice(infoDataPos, infoDataPos + infoSize);
      finalInfoBytes = new Uint8Array(currentInfoData.length + durationElement.length);
      finalInfoBytes.set(currentInfoData, 0);
      finalInfoBytes.set(durationElement, currentInfoData.length);
    }

    // Encode new Info size as 4-byte VINT to ensure enough room without shifting too much
    const newInfoSize = finalInfoBytes.length;
    const newInfoSizeVint = new Uint8Array(4);
    newInfoSizeVint[0] = 0x10 | ((newInfoSize >> 24) & 0x0f);
    newInfoSizeVint[1] = (newInfoSize >> 16) & 0xff;
    newInfoSizeVint[2] = (newInfoSize >> 8) & 0xff;
    newInfoSizeVint[3] = newInfoSize & 0xff;

    // Construct final patched array
    // Part 1: Start up to Info ID (infoPos + 4 bytes for Info ID 0x1549A966)
    const infoIdLen = 4;
    const part1 = bytes.slice(0, infoPos + infoIdLen);
    // Part 2: New Info Size Vint
    const part2 = newInfoSizeVint;
    // Part 3: New Info Data
    const part3 = finalInfoBytes;
    // Part 4: Rest of the file after Info
    const part4 = bytes.slice(infoDataPos + infoSize);

    return new Blob([part1, part2, part3, part4] as unknown as BlobPart[], {
      type: blob.type || 'video/webm',
    });
  } catch (err) {
    console.warn('Failed to patch WebM duration:', err);
    return blob;
  }
}
