/**
 * Fixes duration metadata in WebM files generated by MediaRecorder.
 * Browsers often produce WebM containers without Duration in the EBML Info header,
 * causing Android Gallery, players, and media apps to display 0s, 3s, or disable seeking.
 *
 * This implementation parses the EBML tree using standard variable-length uints
 * and injects/updates the Duration element (0x4489 / 0x489) and TimecodeScale (0x2AD7B1 / 0xAD7B1)
 * so that all players and gallery databases can display and seek the full duration.
 */

interface SectionInfo {
  name: string;
  type: 'Container' | 'Binary' | 'Uint' | 'Int' | 'String' | 'Float' | 'Date';
}

const SECTIONS: Record<number, SectionInfo> = {
  0xa45dfa3: { name: 'EBML', type: 'Container' },
  0x286: { name: 'EBMLVersion', type: 'Uint' },
  0x2f7: { name: 'EBMLReadVersion', type: 'Uint' },
  0x2f2: { name: 'EBMLMaxIDLength', type: 'Uint' },
  0x2f3: { name: 'EBMLMaxSizeLength', type: 'Uint' },
  0x282: { name: 'DocType', type: 'String' },
  0x287: { name: 'DocTypeVersion', type: 'Uint' },
  0x285: { name: 'DocTypeReadVersion', type: 'Uint' },
  0x6c: { name: 'Void', type: 'Binary' },
  0x3f: { name: 'CRC-32', type: 'Binary' },
  0x8538067: { name: 'Segment', type: 'Container' },
  0x14d9b74: { name: 'SeekHead', type: 'Container' },
  0xdbb: { name: 'Seek', type: 'Container' },
  0x13ab: { name: 'SeekID', type: 'Binary' },
  0x13ac: { name: 'SeekPosition', type: 'Uint' },
  0x549a966: { name: 'Info', type: 'Container' },
  0x33a4: { name: 'SegmentUID', type: 'Binary' },
  0x3384: { name: 'SegmentFilename', type: 'String' },
  0xad7b1: { name: 'TimecodeScale', type: 'Uint' },
  0x489: { name: 'Duration', type: 'Float' },
  0x461: { name: 'DateUTC', type: 'Date' },
  0x3ba9: { name: 'Title', type: 'String' },
  0xd80: { name: 'MuxingApp', type: 'String' },
  0x1741: { name: 'WritingApp', type: 'String' },
  0x67: { name: 'Timecode', type: 'Uint' },
  0x654ae6b: { name: 'Tracks', type: 'Container' },
  0x2e: { name: 'TrackEntry', type: 'Container' },
  0x57: { name: 'TrackNumber', type: 'Uint' },
  0x33c5: { name: 'TrackUID', type: 'Uint' },
  0x3: { name: 'TrackType', type: 'Uint' },
  0x60: { name: 'Video', type: 'Container' },
  0x61: { name: 'Audio', type: 'Container' },
  0xc53bb6b: { name: 'Cues', type: 'Container' },
};

class WebmBase {
  name: string;
  type: string;
  source: Uint8Array = new Uint8Array(0);
  data: unknown;

  constructor(name = 'Unknown', type = 'Unknown') {
    this.name = name;
    this.type = type;
  }

  setSource(source: Uint8Array) {
    this.source = source;
    this.updateBySource();
  }

  updateBySource() {}
  updateByData() {}

  setData(data: unknown) {
    this.data = data;
    this.updateByData();
  }
}

function padHex(hex: string): string {
  return hex.length % 2 === 1 ? '0' + hex : hex;
}

class WebmUint extends WebmBase {
  data = '';

  constructor(name = 'Uint', type = 'Uint') {
    super(name, type);
  }

  override updateBySource() {
    this.data = '';
    for (let i = 0; i < this.source.length; i++) {
      const hex = this.source[i].toString(16);
      this.data += padHex(hex);
    }
  }

  override updateByData() {
    const length = this.data.length / 2;
    this.source = new Uint8Array(length);
    for (let i = 0; i < length; i++) {
      const hex = this.data.substring(i * 2, i * 2 + 2);
      this.source[i] = parseInt(hex, 16);
    }
  }

  getValue(): number {
    return parseInt(this.data, 16) || 0;
  }

  setValue(value: number) {
    this.setData(padHex(value.toString(16)));
  }
}

class WebmFloat extends WebmBase {
  data = 0;

  constructor(name = 'Float', type = 'Float') {
    super(name, type);
  }

  getFloatArrayType(): typeof Float32Array | typeof Float64Array {
    return this.source && this.source.length === 4 ? Float32Array : Float64Array;
  }

  override updateBySource() {
    const byteArray = new Uint8Array(this.source).reverse();
    const FloatArrayType = this.getFloatArrayType();
    const floatArray = new FloatArrayType(byteArray.buffer);
    this.data = floatArray[0];
  }

  override updateByData() {
    const FloatArrayType = this.getFloatArrayType();
    const floatArray = new FloatArrayType([this.data]);
    const byteArray = new Uint8Array(floatArray.buffer);
    this.source = byteArray.reverse();
  }

  getValue(): number {
    return this.data;
  }

  setValue(value: number) {
    this.setData(value);
  }
}

interface WebmSectionEntry {
  id: number;
  idHex: string;
  data: WebmBase;
}

class WebmContainer extends WebmBase {
  offset = 0;
  data: WebmSectionEntry[] = [];

  constructor(name = 'Container', type = 'Container') {
    super(name, type);
  }

  readByte(): number {
    return this.source[this.offset++];
  }

  readUint(): number {
    const firstByte = this.readByte();
    const bytes = 8 - firstByte.toString(2).length;
    let value = firstByte - (1 << (7 - bytes));
    for (let i = 0; i < bytes; i++) {
      value *= 256;
      value += this.readByte();
    }
    return value;
  }

  override updateBySource() {
    this.data = [];
    for (this.offset = 0; this.offset < this.source.length; ) {
      const id = this.readUint();
      const len = this.readUint();
      const end = Math.min(this.offset + len, this.source.length);
      const childData = this.source.slice(this.offset, end);

      const info = SECTIONS[id] || { name: 'Unknown', type: 'Unknown' };
      let section: WebmBase;
      switch (info.type) {
        case 'Container':
          section = new WebmContainer(info.name, info.type);
          break;
        case 'Uint':
          section = new WebmUint(info.name, info.type);
          break;
        case 'Float':
          section = new WebmFloat(info.name, info.type);
          break;
        default:
          section = new WebmBase(info.name, info.type);
          break;
      }
      section.setSource(childData);
      this.data.push({
        id,
        idHex: id.toString(16),
        data: section,
      });

      this.offset = end;
    }
  }

  writeUint(x: number, isDraft = false) {
    let bytes = 1;
    let flag = 0x80;
    while (x >= flag && bytes < 8) {
      bytes++;
      flag *= 0x80;
    }

    if (!isDraft) {
      let value = flag + x;
      for (let i = bytes - 1; i >= 0; i--) {
        const c = value % 256;
        this.source[this.offset + i] = c;
        value = Math.floor((value - c) / 256);
      }
    }

    this.offset += bytes;
  }

  writeSections(isDraft = false): number {
    this.offset = 0;
    for (let i = 0; i < this.data.length; i++) {
      const section = this.data[i];
      const content = section.data.source;
      const contentLength = content ? content.length : 0;
      this.writeUint(section.id, isDraft);
      this.writeUint(contentLength, isDraft);
      if (!isDraft && content) {
        this.source.set(content, this.offset);
      }
      this.offset += contentLength;
    }
    return this.offset;
  }

  override updateByData() {
    const length = this.writeSections(true);
    this.source = new Uint8Array(length);
    this.writeSections(false);
  }

  getSectionById(id: number): WebmBase | null {
    for (let i = 0; i < this.data.length; i++) {
      if (this.data[i].id === id) {
        return this.data[i].data;
      }
    }
    return null;
  }
}

class WebmFile extends WebmContainer {
  constructor(source: Uint8Array) {
    super('File', 'File');
    this.setSource(source);
  }

  fixDuration(durationMs: number): boolean {
    // 0x8538067 = Segment
    const segmentSection = this.getSectionById(0x8538067) as WebmContainer | null;
    if (!segmentSection) {
      return false;
    }

    // 0x549a966 = Info
    const infoSection = segmentSection.getSectionById(0x549a966) as WebmContainer | null;
    if (!infoSection) {
      return false;
    }

    // 0xad7b1 = TimecodeScale
    let timeScaleSection = infoSection.getSectionById(0xad7b1) as WebmUint | null;
    if (!timeScaleSection) {
      timeScaleSection = new WebmUint('TimecodeScale', 'Uint');
      infoSection.data.push({ id: 0xad7b1, idHex: 'ad7b1', data: timeScaleSection });
    }

    // 0x489 = Duration
    let durationSection = infoSection.getSectionById(0x489) as WebmFloat | null;
    if (durationSection) {
      durationSection.setValue(durationMs);
    } else {
      durationSection = new WebmFloat('Duration', 'Float');
      durationSection.setValue(durationMs);
      infoSection.data.push({
        id: 0x489,
        idHex: '489',
        data: durationSection,
      });
    }

    // Standardize time scale to 1 millisecond (1,000,000 nanoseconds)
    timeScaleSection.setValue(1000000);

    infoSection.updateByData();
    segmentSection.updateByData();
    this.updateByData();

    return true;
  }

  toBlob(mimeType?: string): Blob {
    return new Blob([this.source.buffer as ArrayBuffer], {
      type: mimeType || 'video/webm',
    });
  }
}

/**
 * Injects or updates the Duration element inside the WebM Segment -> Info header.
 * @param blob Original WebM Blob from MediaRecorder
 * @param durationMs Duration of video in milliseconds
 */
export async function fixWebmDuration(blob: Blob, durationMs: number): Promise<Blob> {
  if (blob.size === 0 || durationMs <= 0) {
    return blob;
  }

  try {
    const arrayBuffer = await blob.arrayBuffer();
    const file = new WebmFile(new Uint8Array(arrayBuffer));
    if (file.fixDuration(durationMs)) {
      return file.toBlob(blob.type);
    }
    return blob;
  } catch (err) {
    console.warn('Failed to patch WebM duration:', err);
    return blob;
  }
}
